name: Build package

on: [workflow_dispatch, workflow_call]

jobs:
  sdist:
    uses: ./.github/workflows/sdist.yml

  wheels:
    uses: ./.github/workflows/wheels.yml

  results:
    needs: [sdist, wheels]
    uses: ./.github/workflows/summary.yml
    with:
      pack: true
