# See https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FORCE_COLOR: 1 # colored output where possible

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-latest, windows-latest]
        py-ver: ["3.7", "3.13"]
        ext: [cython, no-cython] # with/without Cython extension
        exclude:
          - os: macos-latest
            py-ver: "3.7" # not available
          - os: macos-13
            py-ver: "3.13" # to save resources
          # skip no-cython on slower systems
          - os: macos-13
            ext: no-cython
          - os: macos-latest
            ext: no-cython
          - os: windows-latest
            ext: no-cython

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.py-ver }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-ver }}
        cache: "pip"
        cache-dependency-path: setup.py
    - name: Update setup
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install Cython
      if: matrix.ext != 'no-cython'
      # NumPy and Cython must be preinstalled for building Cython extension
      run: python -m pip install numpy cython
    - name: Install pytest
      run: python -m pip install pytest pytest-cov
    - name: Install PyAbel
      run: python -m pip install . -v
    - name: Information
      run: python .github/workflows/info.py
    - name: TESTS
      # "cd .." for coverage of installed abel instead of ./abel subdir
      # summary needs "no-cython" in .json to classify skipped as OK or warning
      run: |
        cd ..
        pytest -v --cov=abel --pyargs abel --log-level=WARN
        python PyAbel/.github/workflows/save-test.py ${{ matrix.ext }}
        python PyAbel/.github/workflows/summary.py msg
