name: Build wheels

on: [workflow_dispatch, workflow_call]

jobs:
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" # for cibuildwheel itself
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.22.0
    - name: Build wheels
      env:
        CIBW_BUILD_VERBOSITY: 1
        # Linux also tries to build i686 (for which NumPy has no binary packages)
        CIBW_ARCHS: "native"
        # "manylinux" should be enough
        CIBW_SKIP: "*musllinux*"
        # build only for Python versions with full support
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.12"
        # preinstall packages required to build with Cython extension
        CIBW_BEFORE_BUILD: "python -m pip install setuptools numpy cython"
        # set env variables for build and test:
        # colored output where possible;
        # don't try to compile NumPy and SciPy from source;
        # disable PEP 517 build isolation, instead use already installed packages
        # (weirdly, must be set to 0, see https://github.com/pypa/pip/issues/5735)
        CIBW_ENVIRONMENT: >
          FORCE_COLOR=1
          PIP_ONLY_BINARY=":all:"
          PIP_NO_BUILD_ISOLATION=0

        CIBW_TEST_REQUIRES: "pytest"
        # calling pytest directly uses wrong python;
        # results can be copied to output (with meaningful name) only manually
        CIBW_TEST_COMMAND: >
          python -m pytest --pyargs abel --log-level=WARN &&
          python {package}/.github/workflows/save-test.py {package} {wheel}
      run: python -m cibuildwheel --output-dir wheels
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.ref_name }}-${{ matrix.os }}
        path: ./wheels/*
